# Generated by Django 5.2.12 on 2026-03-27 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("image", models.ImageField(upload_to="products/")),
                ("description", models.TextField()),
                (
                    "external_link",
                    models.URLField(help_text="Link to Amazon/Gumroad/etc."),
                ),
                (
                    "price_display",
                    models.CharField(help_text="e.g. $9.99", max_length=50),
                ),
            ],
        ),
    ]
