# Generated by Django 5.2.12 on 2026-03-27 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("marketplace", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="WebringSite",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("site_name", models.CharField(max_length=200)),
                ("site_url", models.URLField()),
                ("description", models.CharField(max_length=255)),
                (
                    "approved",
                    models.BooleanField(
                        default=False, help_text="Check this to display it on the site"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name="product",
            name="image",
        ),
        migrations.AddField(
            model_name="product",
            name="image_url",
            field=models.URLField(
                default="",
                help_text="Image URL from Pinterest, Imgur, etc.",
                max_length=500,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="product",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="product",
            name="price_display",
            field=models.CharField(help_text="e.g. $9.99 or FREE", max_length=50),
        ),
    ]
