# Generated by Django 5.2.12 on 2026-03-27 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="post",
            name="image",
        ),
        migrations.AddField(
            model_name="post",
            name="featured_image_url",
            field=models.URLField(
                blank=True,
                help_text="Paste an image URL from Pinterest, Imgur, etc.",
                max_length=500,
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="video_url",
            field=models.URLField(
                blank=True, help_text="Link to YouTube/Vimeo", max_length=500
            ),
        ),
    ]
