# Generated by Django 5.2.12 on 2026-03-27 20:42

import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0003_tag"),
    ]

    operations = [
        migrations.CreateModel(
            name="LegalPage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                (
                    "slug",
                    models.SlugField(help_text="Use 'terms' or 'privacy'", unique=True),
                ),
                ("content", tinymce.models.HTMLField()),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RenameField(
            model_name="comment",
            old_name="text",
            new_name="body",
        ),
        migrations.AddField(
            model_name="comment",
            name="is_approved",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="comment",
            name="author",
            field=models.CharField(max_length=80),
        ),
    ]
