# Generated by Django 5.2.12 on 2026-03-28 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0004_legalpage_rename_text_comment_body_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="SystemStatus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "override_location",
                    models.CharField(default="London", max_length=100),
                ),
                (
                    "override_date",
                    models.DateField(
                        blank=True,
                        help_text="Leave blank to use current system date.",
                        null=True,
                    ),
                ),
                (
                    "active_mood_override",
                    models.CharField(
                        blank=True,
                        help_text="Force a specific mood (e.g., 'Glitchy').",
                        max_length=50,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "System Status",
            },
        ),
        migrations.DeleteModel(
            name="Tag",
        ),
        migrations.AlterModelOptions(
            name="category",
            options={"verbose_name_plural": "Categories"},
        ),
    ]
