# Generated by Django 5.2.12 on 2026-03-28 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0005_systemstatus_delete_tag_alter_category_options"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="systemstatus",
            name="active_mood_override",
        ),
        migrations.RemoveField(
            model_name="systemstatus",
            name="override_date",
        ),
        migrations.RemoveField(
            model_name="systemstatus",
            name="override_location",
        ),
        migrations.AddField(
            model_name="systemstatus",
            name="active_mood",
            field=models.CharField(
                choices=[
                    ("clear", "1. Clear"),
                    ("cloud", "2. Cloud"),
                    ("rain", "3. Rain"),
                    ("storm", "4. Storm"),
                    ("fog", "5. Fog"),
                    ("glitch", "6. Glitch"),
                ],
                default="clear",
                max_length=10,
            ),
        ),
    ]
